# Security Scan Configuration for CI/CD
# This file configures security scanners to ignore known safe third-party components

security_scan:
  # Components to exclude from security reports
  exclude_patterns:
    - "io.flutter.plugins.firebase.messaging.*"
    - "com.google.firebase.iid.*"
    - "com.google.android.gms.auth.api.signin.*"
    - "androidx.profileinstaller.*"
    - "com.google.firebase.auth.internal.*"
    - "com.facebook.CustomTabActivity"
    - "io.flutter.plugins.pathprovider.*"
    - "com.baseflow.permissionhandler.*"
    - "com.it_nomads.fluttersecurestorage.*"
    - "com.tekartik.sqflite.*"
    - "io.flutter.embedding.*"
    - "io.flutter.plugin.*"
    - "io.flutter.plugins.firebase.*"
    - "io.flutter.plugins.imagepicker.*"
    - "io.grpc.internal.*"
    - "io.grpc.okhttp.*"
    - "io.grpc.util.*"
  
  # Security issues to ignore when from trusted sources
  ignore_vulnerabilities:
    - cve: "CWE-276"
      reason: "External storage access - Path provider uses app-private directories"
      sources: ["pathprovider"]
    
    - cve: "CWE-312"
      reason: "Hardcoded information in third-party configuration files"
      sources: ["firebase", "flutter", "grpc", "sqflite", "permissionhandler"]
    
    - cve: "CWE-330"
      reason: "Insecure random in networking libraries - not cryptographic use"
      sources: ["grpc"]
    
    - cve: "CWE-200"
      reason: "IP address disclosure in networking libraries - standard behavior"
      sources: ["grpc"]
    
    - cve: "CWE-89"
      reason: "SQL injection - using parameterized queries in application"
      sources: ["sqflite"]
    
    - cve: "CWE-649"
      reason: "CBC encryption - using latest secure storage version"
      sources: ["fluttersecurestorage"]
  
  # Permissions to ignore when from trusted sources
  ignore_permissions:
    - permission: "com.google.android.c2dm.permission.SEND"
      source: "firebase"
      reason: "Official Google Firebase messaging service"
    
    - permission: "com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"
      source: "google_play_services"
      reason: "Official Google Play Services authentication"
    
    - permission: "android.permission.DUMP"
      source: "androidx"
      reason: "Official AndroidX framework component"

  # Trusted package sources
  trusted_sources:
    - "com.google.firebase"
    - "com.google.android.gms"
    - "androidx"
    - "io.flutter"
    - "com.facebook"
    - "io.grpc"
    - "com.tekartik.sqflite"
    - "com.it_nomads.fluttersecurestorage"
    - "com.baseflow.permissionhandler"

  # Report configuration
  report_format: "filtered"
  include_suppressed_findings: false
  focus_on_app_code: true
  exclude_third_party: true
  documentation_reference: "docs/SECURITY_EXCEPTIONS.md"
  
  # Scan options
  scan_options:
    skip_framework_files: true
    skip_generated_files: true
    skip_test_files: true
    focus_on_custom_code: true
