name: zed_nano
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  bootstrap_icons: ^1.11.3
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  carousel_slider: ^5.1.1
  clarity_flutter: ^1.0.0
  cloud_firestore: ^4.13.6
  connectivity_plus: ^6.1.4
  country_code_picker: ^3.3.0
  csc_picker_plus: ^0.0.3
  currency_country_picker: ^1.2.3
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  fl_chart: ^1.0.0
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_app_loading_indicator: ^0.0.3
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  gif: ^2.3.0
  google_fonts: ^6.2.1
  google_places_autocomplete_text_field: ^1.1.0
  google_sign_in: ^6.3.0
  http: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.2
  local_auth: ^2.3.0
  logger: ^2.5.0
  lottie: ^3.3.1
  nb_utils: ^7.1.4
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  simple_animations: ^5.2.0
  smooth_page_indicator: ^1.2.1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.3.1
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/gifs/

flutter_gen:
  output: lib/gen/
  line_length: 80
  
  # Configure integrations
  integrations:
    flutter_svg: true
