name: zed_nano
description: A Very Good Project created by Very Good CLI.
version: 1.0.4+4
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  clarity_flutter: ^1.0.0
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.4
  country_code_picker: ^3.3.0
  csc_picker_plus: ^0.0.3
  currency_country_picker: ^1.2.3
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  firebase_storage: ^13.0.0
  flutter_local_notifications: ^18.0.1
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  gif: ^2.3.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  http: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  infinite_scroll_pagination: 4.1.0
  intl: ^0.20.2
  logger: ^2.5.0
  nb_utils: ^7.1.4
  package_info_plus: ^8.3.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^12.0.0+1
  printing: ^5.13.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  top_snackbar_flutter: ^3.3.0
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.3
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/gifs/

flutter_gen:
  output: lib/gen/
  line_length: 80
  
  # Configure integrations
  integrations:
    flutter_svg: true
